name: Check PR

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PROJECT: app-pizza-hawaii

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ env.PROJECT }}:latest
          outputs: type=docker,dest=/tmp/${{ env.PROJECT }}.tar
          secrets: |
            "npm_token=${{ env.NPM_TOKEN }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT }}
          path: /tmp/${{ env.PROJECT }}.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PROJECT }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.PROJECT }}.tar

      - name: Run image
        run: |
          docker run -d -p 3000:3000 ${{ env.PROJECT }}:latest --name ${{ env.PROJECT }} --env NODE_AUTH_TOKEN ${{ secrets.NPM_TOKEN }} --env NEXTAUTH_URL ${{ secrets.NEXTAUTH_URL }} --env NEXTAUTH_SECRET ${{ secrets.NEXTAUTH_SECRET }} --env NEXT_PUBLIC_QWACKER_API_URL ${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }} --env ZITADEL_ISSUER ${{ secrets.ZITADEL_ISSUER }} --env ZITADEL_CLIENT_ID ${{ secrets.ZITADEL_CLIENT_ID }} --env NEXT_PUBLIC_VERCEL_URL ${{ secrets.NEXT_PUBLIC_VERCEL_URL }}
