name: Deploy Pizza Docker Container with Terraform to GCP

on:
  push:
    branches: ['main', 'feature/*']
  pull_request:
    branches: ['main', 'feature']
  workflow_dispatch:
    
concurrency:
  group: 'release'
  cancel-in-progress: true
 
env:
    REGISTRY: 'europe-west6-docker.pkg.dev'
    OWNER: 'project-pizza-388116/pizza-repo'
    REPOSITORY: 'app-pizza-hawaii'
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
    NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    NEXT_PUBLIC_QWACKER_API_URL: ${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }}
    ZITADEL_ISSUER: ${{ secrets.ZITADEL_ISSUER }}
    ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
    NEXT_PUBLIC_VERCEL_URL: ${{ secrets.NEXT_PUBLIC_VERCEL_URL }}

jobs:
    release:
      name: Create Release
      runs-on: ubuntu-latest
      permissions: write-all
  
      steps:
        - uses: actions/checkout@v3

        #  Build and push Docker image to Google Artifact Registry
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.NPM_TOKEN }}
            
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: 'projects/654053669202/locations/global/workloadIdentityPools/casfee23-pool/providers/casfee23-provider'
            service_account: 'casfee23-account@project-pizza-388116.iam.gserviceaccount.com'
            token_format: 'access_token'
  
        - name: Login to Google Artifact Registry
          uses: docker/login-action@v2
          with:
            registry: europe-west6-docker.pkg.dev
            username: 'oauth2accesstoken'
            password: '${{ steps.auth.outputs.access_token }}'
  
        - 
          name: Build and push Docker image to ${{ env.REGISTRY }}
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            secrets: |
              "npm_token=${{ secrets.NPM_TOKEN }}"
            tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPOSITORY }}:latest 
            
        - name: Install the App on Artifact Registry a cloudRun Container with terraform
          uses: hashicorp/setup-terraform@v2
        - run: terraform init
          working-directory: terraform
        - run: terraform validate
          working-directory: terraform  
        - run: terraform apply -auto-approve
          working-directory: terraform  #,${{ github.sha }}
  