name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'main'
  cancel-in-progress: true

jobs:
  main-lint-and-prettier:
    name: Code Quality Image
    uses: ./.github/workflows/task-lint-and-prettier.yml
    secrets: inherit

  main-unit-tests:
    name: Unit Tests
    needs: main-lint-and-prettier
    uses: ./.github/workflows/task-unittests.yml
    secrets: inherit

  main-docker-build-and-publish:
    if: success()
    name: Build and Publish Docker Image
    needs: main-unit-tests
    uses: ./.github/workflows/task-docker-push.yml
    with:
      registry: github
      tags: |
        ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
      base_url: https://app-pizza-hawaii-rcosriwdxq-oa.a.run.app
    secrets: inherit

  main-playwright-e2e:
    if: success()
    name: E2E Tests on Docker Image
    needs: main-docker-build-and-publish
    uses: ./.github/workflows/task-playwright-e2e.yml
    with:
      image: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  main-web-vitals:
    if: success()
    name: Web Vitals on Docker Image
    needs: main-docker-build-and-publish
    uses: ./.github/workflows/task-web-vitals.yml
    with:
      image: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
      test_url: http://localhost:3000/mumble/01GYX2NAVWCNCQNX7RV5SZARJK
    secrets: inherit

  main-retag-docker:
    if: success()
    name: Retag Docker (Test / GitHub Container Registry)
    needs: [main-docker-build-and-publish, main-playwright-e2e, main-web-vitals]
    uses: ./.github/workflows/task-docker-retag.yml
    with:
      registry: google
      src: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
      dst: europe-west6-docker.pkg.dev/project-pizza-388116/pizza-repo/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  main-deploy-google-cloud:
    if: success()
    name: Deploy to Google Cloud Run Registry
    needs: [main-playwright-e2e, main-web-vitals]
    uses: ./.github/workflows/task-deploy.yml
    with:
      hoster: google-cloud
      image: europe-west6-docker.pkg.dev/project-pizza-388116/pizza-repo/app-pizza-hawaii:${{ github.sha }}
      url: https://app-pizza-hawaii-rcosriwdxq-oa.a.run.app
    secrets: inherit

  main-playwright-e2e-deployed:
    if: success()
    name: E2E Tests on Live Environment
    needs: [main-deploy-google-cloud]
    uses: ./.github/workflows/task-playwright-e2e.yml
    with:
      test_url: https://app-pizza-hawaii-rcosriwdxq-oa.a.run.app
    secrets: inherit
