name: Pull Request Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'main'
  cancel-in-progress: true

jobs:
  m-lint-and-prettier:
    name: Lint and Prettier
    uses: ./.github/workflows/task-lint-and-prettier.yml
    secrets: inherit

  m-docker-build-and-publish:
    if: success()
    name: Build and Publish Docker (Test / GitHub Container Registry)
    needs: pr-lint-and-prettier
    uses: ./.github/workflows/task-docker-push.yml
    with:
      registry: google
      tags: |
        europe-west6-docker.pkg.dev/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  m-playwright-e2e:
    if: success()
    name: E2E Tests on Docker
    needs: pr-docker-build-and-publish
    uses: ./.github/workflows/task-playwright-e2e.yml
    with:
      image: europe-west6-docker.pkg.dev/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  m-web-vitals:
    if: success()
    name: Web Vitals on Docker
    needs: pr-docker-build-and-publish
    uses: ./.github/workflows/task-web-vitals.yml
    with:
      image: europe-west6-docker.pkg.dev/smartive-education/app-pizza-hawaii:${{ github.sha }}
      test_url: http://localhost:3000/mumble/01GYX2NAVWCNCQNX7RV5SZARJK
    secrets: inherit

  m-deploy-google-cloud:
    if: success()
    name: Deploy to Google Cloud Run Registry
    needs: [pr-docker-build-and-publish, pr-playwright-e2e, pr-web-vitals]
    uses: ./.github/workflows/task-deploy.yml
    with:
      hoster: google-cloud
    secrets: inherit

  m-deploy-vercel:
    if: success()
    name: Deploy to Vercel Hosting
    needs: [pr-docker-build-and-publish, pr-playwright-e2e, pr-web-vitals]
    uses: ./.github/workflows/task-deploy.yml
    with:
      hoster: vercel
    secrets: inherit

  # m-notify:
  #   if: success()
  #   name: Notify Slack
  #   needs: pr-deploy
  #   uses: ./.github/workflows/task-notify.yml
  #   secrets: inherit
