name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pr-lint-and-prettier:
    name: Lint and Prettier
    uses: ./.github/workflows/tasks/lint-and-prettier.yml
    secrets: inherit

  pr-docker-build-and-publish:
    # if: success()
    name: Build and Publish Docker image
    # needs: pr-lint-and-prettier
    uses: ./.github/workflows/tasks/docker-push.yml
    with:
      registry: github
      tags: |
        ghcr.io/smartive-education/app-pizza-hawaii:test
        ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  pr-playwright-e2e:
    if: success()
    name: E2E Tests on Docker
    needs: pr-docker-build-and-publish
    uses: ./.github/workflows/tasks/playwright-e2e.yml
    with:
      image: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit
