name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test-playwright-e2e-deployed:
    name: E2E Tests on Live Environment
    uses: ./.github/workflows/task-playwright-e2e.yml
    with:
      test_url: https://app-pizza-hawaii-rcosriwdxq-oa.a.run.app
    secrets: inherit
