name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pr-lint-and-prettier:
    name: Lint and Prettier
    uses: ./.github/workflows/task-lint-and-prettier.yml
    secrets: inherit

  pr-docker-build-and-publish:
    if: success()
    name: Build and Publish Docker (Test / GitHub Container Registry)
    needs: pr-lint-and-prettier
    uses: ./.github/workflows/task-docker-push.yml
    with:
      registry: github
      tags: |
        ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  pr-playwright-e2e:
    if: success()
    name: E2E Tests on Docker
    needs: pr-docker-build-and-publish
    uses: ./.github/workflows/task-playwright-e2e.yml
    with:
      image: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  pr-web-vitals:
    if: success()
    name: Web Vitals on Docker
    needs: pr-docker-build-and-publish
    uses: ./.github/workflows/task-web-vitals.yml
    with:
      image: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
      test_url: http://localhost:3000/mumble/01GYX2NAVWCNCQNX7RV5SZARJK
    secrets: inherit

  # TODO: remove this once it works
  pr-deploy-google-cloud:
    if: success()
    name: Deploy to Google Cloud Run Registry
    needs: [pr-docker-build-and-publish, pr-playwright-e2e, pr-web-vitals]
    uses: ./.github/workflows/task-deploy.yml
    with:
      hoster: google-cloud
    secrets: inherit

  pr-deploy-vercel:
    if: success()
    name: Deploy to Vercel Hosting
    needs: [pr-docker-build-and-publish, pr-playwright-e2e, pr-web-vitals]
    uses: ./.github/workflows/task-deploy.yml
    with:
      hoster: vercel
    secrets: inherit
