name: Stage Workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: 'stage'
  cancel-in-progress: true

jobs:
  stage-lint-and-prettier:
    name: Code Quality
    uses: ./.github/workflows/task-lint-and-prettier.yml
    secrets: inherit

  stage-unit-tests:
    name: Unit Tests
    needs: stage-lint-and-prettier
    uses: ./.github/workflows/task-unittests.yml
    secrets: inherit

  stage-docker-build-and-publish:
    if: success()
    name: Build and Publish Docker Image
    needs: stage-unit-tests
    uses: ./.github/workflows/task-docker-push.yml
    with:
      registry: github
      tags: |
        ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  stage-playwright-e2e:
    if: success()
    name: E2E Tests on Docker Image
    needs: stage-docker-build-and-publish
    uses: ./.github/workflows/task-playwright-e2e.yml
    with:
      image: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
    secrets: inherit

  stage-web-vitals:
    if: success()
    name: Web Vitals on Docker Image
    needs: stage-docker-build-and-publish
    uses: ./.github/workflows/task-web-vitals.yml
    with:
      image: ghcr.io/smartive-education/app-pizza-hawaii:${{ github.sha }}
      test_url: http://localhost:3000/mumble/01GYX2NAVWCNCQNX7RV5SZARJK
    secrets: inherit

  stage-deploy-vercel:
    if: success()
    name: Deploy to Vercel Hosting
    needs: [stage-docker-build-and-publish, stage-playwright-e2e]
    uses: ./.github/workflows/task-deploy.yml
    with:
      hoster: vercel
    secrets: inherit
