name: Create Docker image and push to registry

on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: Package registry to push to
        default: 'github'
        required: true

      tags:
        type: string
        description: Docker tags to push
        required: true
        default: 'ghcr.io/smartive-education/app-pizza-hawaii:test'
      labels:
        type: string
        description: Docker labels to push

permissions:
  contents: read
  packages: write

jobs:
  github-cr:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    if: ${{ inputs.registry == 'github' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.NPM_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
          secrets: |
            "npm_token=${{ secrets.NPM_TOKEN }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  google-cr:
    name: Build and push Docker image to Google Container Registry
    runs-on: ubuntu-latest
    if: ${{ inputs.registry == 'google' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/654053669202/locations/global/workloadIdentityPools/casfee23-pool/providers/casfee23-provider'
          service_account: 'casfee23-account@project-pizza-388116.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Login to Google Cloud
        uses: docker/login-action@v2
        with:
          registry: 'europe-west6-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
          secrets: |
            "npm_token=${{ secrets.NPM_TOKEN }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
