#
# Jest and RTL Test workflow to test on braches and pull requests
#

name: Jest and RTL Test Deployment

on:
  pull_request:
    branches: [main, feature/*]

jobs:
  testing-with-jest:
    name: Run test cases with Jest and React Test Library🤞
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run tests
        run: npm run test-unit
