name: Jest and RTL Test

on:
  workflow_call:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  testing-with-jest:
    name: Run test cases with Jest and React Test Library🤞
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
      - name: Run tests
        run: npm run test-unit
