name: Web Vitals

on:
  workflow_call:
    inputs:
      image:
        description: 'The image to test with (optional)'
        default: ''
        type: string

      test_url:
        description: 'The URL to test'
        default: 'http://localhost:3000'
        type: string

jobs:
  web-vitals-on-image:
    if: ${{ inputs.image != '' }}
    name: Web Vitals
    runs-on: ubuntu-latest
    services:
      app:
        image: ${{ inputs.image }}
        ports:
          - 3000:3000
        env:
          NEXT_PUBLIC_VERCEL_URL: ${{ inputs.test_url }}
          NEXTAUTH_URL: ${{ inputs.test_url }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_QWACKER_API_URL: ${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }}
          ZITADEL_ISSUER: ${{ secrets.ZITADEL_ISSUER }}
          ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.url=${{ inputs.test_url }} --collect.numberOfRuns=3 --upload.target=temporary-public-storage --upload.token=${{ secrets.NPM_TOKEN }}

      - id: read-manifest
        run: |
          echo ::set-output name=manifest::$(cat .lighthouseci/manifest.json)
      - uses: actions/github-script@v4
        if: github.event.context == 'deploy/netlify' && github.event.state == 'success'
        env:
            MANIFEST: ${{ steps.read-manifest.outputs.manifest }}
        with:
          script: |
            const manifest = JSON.parse(process.env.MANIFEST);
            console.log('\n\n\u001b[32mSummary Results:\u001b[0m');

            var rows = manifest.map((row) => {
              return {
                "url": row.url.substring(row.url.indexOf("netlify.app") + 11),
                "performance": row.summary.performance,
                "accessibility": row.summary.accessibility,
                "seo": row.summary.seo
              }
            });

            console.table(rows);
  web-vitals-on-url:
    if: ${{ inputs.image == '' }}
    name: Web Vitals on URL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.url=${{ inputs.test_url }} --collect.numberOfRuns=3 --upload.target=temporary-public-storage --upload.token=${{ secrets.NPM_TOKEN }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}


      - id: read-manifest
        run: |
          echo ::set-output name=manifest::$(cat .lighthouseci/manifest.json)
      - uses: actions/github-script@v4
        if: github.event.context == 'deploy/netlify' && github.event.state == 'success'
        env:
            MANIFEST: ${{ steps.read-manifest.outputs.manifest }}
        with:
          script: |
            const manifest = JSON.parse(process.env.MANIFEST);
            console.log('\n\n\u001b[32mSummary Results:\u001b[0m');

            var rows = manifest.map((row) => {
              return {
                "url": row.url.substring(row.url.indexOf("netlify.app") + 11),
                "performance": row.summary.performance,
                "accessibility": row.summary.accessibility,
                "seo": row.summary.seo
              }
            });

            console.table(rows);
